#!/usr/bin/perl

open(IN, "historical");
while (<IN>) {
	next if /^$/;
	next if /http/;
	next if /#/;

	if (/^([0-9]+):/) {
		$year = $1;
		$sum = 0;
		open(OUT, ">out/$year");
		# print OUT "1 1\n";
	} elsif (/^([0-9]+)\s+([0-9]+)/) {
		$sum += $2;
		if ($1 != 1) {
			print OUT "$1 $sum ($2)\n";
		}
	} elsif (/^(max)\s+([0-9]+)/) {
		$sum += $2;
		print OUT "$1 $sum ($2)\n";
	} else {
		die "??? $_";
	}
}
